repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
    files: .github/
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: cargo-test
    name: cargo test
    entry: make test
    language: system
    pass_filenames: false
  - id: cargo-fmt
    name: cargo fmt
    entry: make fmt
    language: system
    pass_filenames: false
  - id: cargo-clippy
    name: cargo clippy
    entry: make lint
    language: system
    pass_filenames: false
