version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/wwwroot/:/etc/nginx/html
    ports:
    - "80:80"

  postgres:
    image: postgres:16.1-bullseye
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build:
      context: opday-dev
    command: cargo run
    restart: unless-stopped
    ports:
      - 3003:3003
    environment:
      DATABASE_DSN: postgresql://postgres:postgres@localhost:5432/postgres
