version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/wwwroot/:/etc/nginx/html
    - type: bind
      source: /root/.acme.sh/opday.dev_ecc/
      target: /root/.acme.sh/opday.dev_ecc/
      read_only: true
    - type: bind
      source: /etc/nginx/cert
      target: /etc/nginx/cert
      read_only: true
    ports:
    - "80:80"
    - "443:443"

  backend:
    image: registry.digitalocean.com/frlr/opday-dev/backend:$BACKEND_TAG
    build: '!reset null'
    command: opday-dev -p 3003
    restart: unless-stopped
    ports:
    - 3003:3003
