name: Deploy

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download opday
      run: |
        wget -O opday https://github.com/aptakhin/opday/releases/download/0.0.1/opday-x86_64-unknown-linux
        chmod +x opday
    - name: Build
      run: make deploy
